### ISSUE TITLE
Invalid application key (5) (Hallon::Error)

### ISSUE THREAD

**Issue by paulsturgess** [Burgestrand/Hallon#106]
I'm trying to run the playing_audio example.

I can enter my username and password and I have dropped the binary version of my spotify_appkey.key in the right location.

However after I enter my password I get:

gems/hallon-0.15.0/lib/hallon/error.rb:68:in `maybe_raise': [BAD_APPLICATION_KEY] Invalid application key (5) (Hallon::Error)

Any ideas?

**Comment by Burgestrand** [comment]
Hm. Hallon passes the application key straight to libspotify after reading it from the file using IO#read. I have two theories.
1. Your application key is somehow corrupt, or really _is_ not an application key.
2. Your application key contains a sequence of bytes that I Hallon should be able to handle, but isn't.

Given I'm only using my own application key it's possible Hallon cannot handle all application keys in existence. More specifically I'm thinking of if they contain NUL-bytes. I' not sure how Hallon handles that, but I should be able to have a look in about two hours.

One thing that could help with debugging is if you'd feel comfortable enough sending me your application key so I could debug with it. Keep in mind I'm not sure they are not easily changed from Spotifys website (although it should be possible via email to them). If you do send it to me, please send it to the email listed on my GitHub profile @Burgestrand.

**Comment by Burgestrand** [comment]
Turns out the application keys you get from libspotify developer site at the moment have an incorrect formatting. The developers know about it and are looking at it now. Hopefully they’ll fix it soon enough!

I’m writing a script to convert the bad ones as we speak. I’ll upload it when it is available.

**Comment by Burgestrand** [comment]
I’ve written a converter to fix bad application keys in ef47cb4091bf0e1a4df9a67790696d95880d81f0: https://github.com/Burgestrand/Hallon/blob/master/dev/application_key_converter.rb

@paulsturgess I’ve emailed you a new application key that should work. I’m closing this issue for now, and if it still does not work we’ll reopen it and have another look. :)
