### ISSUE TITLE
Friend listens

### ISSUE THREAD

**Issue by xbora** [Burgestrand/Hallon#134]
Hi, is it at all possible in the Spotify API (or Hallon) to get my Spotify friends' starred tracks and playlists? I didn't see this anywhere in the docs but just wanted to ask here before giving up on it.

Thanks.
Bora

**Comment by Burgestrand** [comment]
You can’t get a list of your friends from libspotify, they removed that functionality when they added facebook, but that does not necessarily stop us.

If you have the Spotify name of somebody (e.g. mine, `Burgestrand`), you can create a user from it. Unfortunately I’ve been unsuccessful in retrieving user information from people who signed up to Spotify through Facebook — it might be the case that libspotify does not support facebook users just yet.

Anyhow, once you have a Hallon::User (you can create one with e.g. [Hallon::User.new("spotify:user:Burgestrand")](http://rdoc.info/github/Burgestrand/Hallon/Hallon/User#initialize-instance_method)), you can retrieve [published playlists of that user](http://rdoc.info/github/Burgestrand/Hallon/Hallon/User#published-instance_method), as well as the [starred playlist for that user](http://rdoc.info/github/Burgestrand/Hallon/Hallon/User#starred-instance_method).

There is an [example in the hallon examples that lists all published playlists of a user by name](https://github.com/Burgestrand/Hallon/blob/master/examples/show_published_playlists_of_user.rb).

PS: questions are best served on the mailing list: https://groups.google.com/forum/#!forum/ruby-hallon :)

**Comment by xbora** [comment]
Thanks for the quick response. Just like I thought... (sigh)

I did actually play with that example you gave above and checked a few of my friends' playlists this way but I think this only looks at public playlists? Because when I log in the same user with a password I see more playlists then just looking up by username. And sometimes when I know that my friend has a ton of playlists I can see inside of Spotify, looking up with the code example above returns an empty list. I imagined it was because it was an unauthenticated call.

This is one bit Rdio has a leg up over Spotify because you can look up a user's friends and their collections without even authenticating, which is very nice "and social".

**Comment by Burgestrand** [comment]
Yes.

If you look at your profile in the Spotify client (top right, click your name and go to `Profile`), you can edit your public profile by clicking at the `Edit` button at the top. Once you do that you’ll be able to select which playlists are published (i.e. visible by other users looking at your profile), and which playlists that are hidden (i.e. only visible by you when logged in).

In the application settings of the Spotify client, there is a configuration setting that says “Automatically publish new playlists”, which toggles if newly created playlists are hidden or public — I believe this setting is set to public by default.

Hallon should be able to see all playlists that are published of a user, the same list of playlists you’ll see of a user if you visit their profile in the Spotify client. I definitely can see the need for private playlists that is opt-in.
