### ISSUE TITLE
Facebook Logins to Spotify

### ISSUE THREAD

**Issue by xbora** [Burgestrand/Hallon#135]
Hey Kim,

Some of the users of my app dont have Spotify usernames as they use Spotify via their Facebook credentials. Do you know of a way to handle these types of users, since I can't log them in via Hallon without credentials?

Thanks.
Bora

**Comment by Burgestrand** [comment]
I have good news for you. [Session#login](http://rdoc.info/github/Burgestrand/Hallon/Hallon/Session#login-instance_method) accepts a facebook e-mail and password! So, if logging in to facebook with `b@m.an` as email, and `rob!n` as password on facebook.com, you can use the e-mail as username, and password as password, when logging in with Hallon.

**Comment by xbora** [comment]
That's great to hear. Thanks Kim!
