### ISSUE TITLE
Non Premium user error

### ISSUE THREAD

**Issue by xbora** [Burgestrand/Hallon#136]
Hi Kim,

Sorry to keep opening non-Hallon issues here but it seems you're the only man with answers to my questions and I don't have your direct email.

For some of my users, I see this error when they are trying to connect their Spotify account:

Hallon::Error: [USER_NEEDS_PREMIUM] Needs a premium account (15)

Does that mean we can't use Hallon for free Spotify users?

Thanks.
Bora

**Comment by Burgestrand** [comment]
Yes, you need a premium account. It’s the number one point in the [Hallon prerequisites in the README](https://github.com/Burgestrand/Hallon#prerequisites). An unlimited, or free, account is not sufficient.

[My contact details are also found in the README](https://github.com/Burgestrand/Hallon#contact-details), as well as the link to the [Hallon mailing list](https://groups.google.com/d/forum/ruby-hallon), which is made for questions like these.
