### ISSUE TITLE
Getting a playlist's id/href

### ISSUE THREAD

**Issue by aurels** [Burgestrand/Hallon#138]
Hello,

I can't figure out how to get a playlist's href.

I am successfully able to create a playlist with `container.add` and I get a `Hallo::Playlist` instance. I then upload it, and I can see it on Spotify.  But how can I get from this instance the href/url/id to store it on our side ?  I can't find the method to use :-p

Thanks in advance,

Aurels

**Comment by Burgestrand** [comment]
Please use the mailing list: https://groups.google.com/forum/#!forum/ruby-hallon — issue reports are not for questions.
