### ISSUE TITLE
Deadlock when loading search results

### ISSUE THREAD

**Issue by elliottwilliams** [Burgestrand/Hallon#142]
I'm unable to load any search results (so far) without deadlocking Hallon.
For example (having already connected and opened a session): 

``` ruby
s = Hallon::Search.new("the decemberists")
s.load
```

will lock everything up.

Could this be something gone wrong on libspotify's side? 
I'm using Ruby 1.9.3, Hallon 0.18.1, and FFI 1.6.0.

Thanks so much for all your work thus far!

**Comment by Burgestrand** [comment]
Try downgrading to FFI latest 1.3.x. I noticed an issue with newer FFI versions that seem to make everything to lock up on my machine.

As far as libspotify’s side, the thing that mostly go wrong is that objects don’t load. It should not be deadlocking (i.e. unable to quit program, even with ^C), that’s Hallon’s fault.

**Comment by elliottwilliams** [comment]
That did it. Thanks!
