### ISSUE TITLE
Playlist creation is not always reflected on other clients

### ISSUE THREAD

**Issue by Burgestrand** [Burgestrand/Hallon#2]
The tests, for example, will create a playlist named “rspec” and another named “omgwtfbbq”. Both of these are rarely (if ever) added to the container on the Spotify servers, nor actually uploaded.

When a playlist has been created it should exist everywhere, not just in local memory.

**Comment by Burgestrand** [comment]
The tests exit very quickly, which is the reason to why the playlists aren’t created on Spotify’s servers. The playlist callbacks could be used to signal when the playlist is properly saved.

**Comment by Burgestrand** [comment]
Logging out to force-flush data does resolve the issue somewhat. It is not reliable, however. A dude in Spotify IRC said they would address it to the devs.

**Comment by jimneath** [comment]
Any update on this issue?

I'm currently using the obsolete branch against 0.0.6 and sometimes playlists are created (although it can take minutes before its reflected on the server) other times they aren't.

Also sometimes the tracks are populated, other times they are not.

Will this be sorted with the new master branch or is this still an issue with Spotify itself?

Many thanks for making this wrapper btw :)

**Comment by Burgestrand** [comment]
`libspotify` has some callbacks on playlists related to this, as well as [sp_playlist_has_pending_changes](http://developer.spotify.com/en/libspotify/docs/group__playlist.html#gaf0e39b5969259d10625eb398af0f3f43) (Playlist#pending?).

For v0.0.4 (the version I originally used `obsolete` branch for), it had a bug in the `sp_playlist_has_pending_changes` function, always returning the same value. Since the `obsolete` branch does not handle callbacks either, there was no way to check if playlists had been persisted to Spotify.

The `master` branch handles libspotify callbacks, which means they can be used to know when a playlist has been persisted, and not exit until that is done. Assuming libspotify has no bugs related to the callbacks (and that I do not misinterpret their meaning), the issue have been resolved once I actually implement playlists in the master branch!

However, since you run 0.0.6, there is a chance the bug in the `Playlist#pending?` function might have been fixed. In that case, you might be able to poll:

```
# assuming changed_playlists is an array of playlists you’ve changed
until changed_playlists.empty?
  sleep 0.1 while session.process_events == 0 # give time between each event processing
  changed_playlists.select!(&:pending?) # only keep non-updated playlists
  sleep 0.1 # avoid CPU-intensive looping
end
```

Be very cautious of this code: I have not tested it, but I do know it will not work on 0.0.4. What it does is that it loops forever, allowing libspotify to do some processing and then checks each playlist if it has been uploaded to Spotify. If it has, it is removed from the playlists we care about, and it starts over, checking the rest of them.

**Comment by jimneath** [comment]
Thanks for the speedy and thorough response.

I'll try the callback with the obsolete branch and 0.0.6. If it doesn't work, I'll wait until the master branch has playlist integration :)

**Comment by Burgestrand** [comment]
I’ll do my best to not have it be too long of a wait; I’ve had a hard time managing my time lately >:(

**Comment by Burgestrand** [comment]
An update on this: after a discussion in the #spotify IRC channel on freenode, it appears libspotify version **0.0.7** (and most likely lower) has this bug as well. It is unclear if it will persist until 0.0.8, but they (names unsaid) did mention “I should really fix that before 0.0.8 :(”

The proposed fix was to try and create a link of the playlist one wishes to check for loaded status; if the link is successfully created (link pointer not null) and `Playlist#loaded?` returns true, the playlist is loaded.

Best place to control this without having to resort to polling is to wait for the `playlist_state_change` callback before checking again. Once again, `obsolete` branch does not support callbacks >:(

Side note: I have noticed that creating a playlist will fire the “playlist_added” callback immediately, but it will not appear in your desktop client until the “container_loaded” callback has fired. Will try to remember this when I implement the callbacks.

**Comment by Burgestrand** [comment]
Did some checking on this just now.

It appears libspotify v9 has a (fairly) working `sp_playlist_has_pending_changes` function, in such that it returns true for newly created playlists until they’re stored on the server. Once this function returned false, my newly created playlist could be seen in my Spotify client.

In short: it was a bug in libspotify, but it appears to be fixed in **v9**! It means I can finally close this issue. :)

On a related note I’m doing a release today, but it does not have playlist or playlist container support. Those two things are the last things to implement before I have 100% API coverage, so they’ll be next.

**Comment by Burgestrand** [comment]
Should add a note to this: after adding tracks to a playlist, you need to call Session#process_events at least _once_ before calling Playlist#pending? or it’ll return false.
