### ISSUE TITLE
Hallon and Resque don’t like each other

### ISSUE THREAD

**Issue by Burgestrand** [Burgestrand/Hallon#48]
For some reason, requiring Resque and Hallon at the same time seem to cause things to come to a deadlock.

To reproduce, one should:
1. Create a brand new Rails 3.0.x application (might not be necessary with rails, but it’s what we had just now).
2. Add Hallon (HEAD) and Resque to the Gemfile.
3. Start the console.
4. Create a session.
5. Log in to Spotify.
6. Create a Link, a Track or whatever. Process events and stuff; just using Hallon causes it to hang.

**Comment by emil-palm** [comment]
I found a small workaround for this;

In lib/hallon/link.rb:16 you can change:
`link = Spotify.link_create_from_string!(spotify_uri.to_s)`
into
`link = Spotify.link_create_from_string(spotify_uri.to_s)`

It stops occuring atleast in "rails c"

**Comment by Burgestrand** [comment]
Thanks for sticking to it! Originally, I thought this was strange, but I have a theory now. Long story short, sp_link_create_from_string in libspotify might sometimes call callbacks, which is bad if the function is not marked as blocking in FFI.

This behaviour is not documented in libspotify, but it would not be the first time I suspect this. I only managed to reproduce this hanging on my GFs computer, and that’s only about once every 20-30 runs. I need to collect some more gdb backtraces.

**Comment by Burgestrand** [comment]
Turns out that theory is an actual (but very rare) issue, but not related to this one. This particular issue is due to forking, and I’ll add a note about it to the README before I close this.
