### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by sahilTakiar** [Burgestrand/Hallon#64]
Hey, had a quick question about Hallon and libspotify in general I was hoping you could help me with. Does libspotify actually allow the streaming of its music through a third party application? Also, does Hallon support the streaming of music? In general, what are the capabilities of Hallon compared to Spotify itself?

Thanks for the help!

**Comment by Burgestrand** [comment]
Hi!

Hallon has, in the writing moment, support for every part of the libspotify API. If you can do it with libspotify, you should be able to do it with Hallon as well. An API reference for Hallon can be found on rdoc.info: http://rubydoc.info/github/Burgestrand/Hallon/master/frames — I’m constantly trying to improve the documentation, so if anything’s confusing in it just give me a shout and I’ll try to clear it up both for you and in the documentation itself.

With that said, libspotify allows you to do all things that the Spotify client allows you to do, with the exception of (not necessarily an exhaustive list):
- spotify social features (no listing friends, seeing what they’re listening to and such)  
  it used to allow you listing friends, but they removed that feature as well; I believe they want you to use
  the facebook graph api if you want to do something similar yourself
- nothing related to spotify apps
- any kind of purchasing
- syncing local music (tracks you’ve added yourself) to devices
- play queue (you have to manage this yourself)

However, libspotify _does_ allow you to:
- get information from albums, artists, playlists, playlist containers, tracks, and users (see api reference for exactly what kind of information)
- retrieve artwork of albums, artist portraits (and I believe something more that I’ve forgotten)
- create and manipulate playlists on behalf of the logged in user; adding tracks, removing tracks, renaming playlists and such
- search for tracks, albums, artists
- radio searches for certain genres and time periods
- browse album, artist and track toplists for a user, a region or everywhere
- it has offline support (but I’ve yet to use this myself, even from within Hallon), even offline-syncing tracks
- stream music (right now, however, the support is limited to giving you the raw audio as an array of integers in a callback)

… and possibly a bunch of more things.

I’d love to write more about it but I’m in a hurry and have to leave. See the examples/ directory for an example of how to play audio, https://github.com/Burgestrand/Hallon/blob/master/examples/playing_audio.rb

PS: I’m working on writing some audio drivers using OpenAL as well (that should work on linux), but that’s not yet done.

**Comment by Burgestrand** [comment]
Oh; another thing. I'm working on improving the audio API, so expect changes on how audio is to be played in the future (most changes will be on the Hallon::Player API). See #59 for the related issue and updates on that.

**Comment by Burgestrand** [comment]
Closing this discussion; if you have more related questions feel free to reopen it (or send an email :)).
