### ISSUE TITLE
AirPlay driver

### ISSUE THREAD

**Issue by Burgestrand** [Burgestrand/Hallon#80]
In theory, it is possible to write a driver for Hallon that allows you to stream audio directly to any AirPlay receiver.

Did some initial homework, and it appears one needs to support the AirPlay v2 protocol in order to get spotless playback.

See http://git.zx2c4.com/Airtunes2/about for protocol information.

There is also https://github.com/elcuervo/airplay — it does not appear to support audio streaming (at least no mention of it in the readme), but it'd be interesting to see where the author has found out details of the protocol.

**Comment by hamin** [comment]
@Burgestrand of course you know how I feel about this one :). However, I don't think this is possible at the moment. From all the cracked AirPlay v2 protocols I've seen, you point to a file (either public or local). I've seen several nodejs AirPlay clients do the same thing. It may be that the protocol headers may require the media files to be present as opposed to being piped bit by bit. I may be wrong but after researching this for a while, all solutions lead to pointing to a full file. Let me know if you make any progress on this or if I can help in any way.

**Comment by Burgestrand** [comment]
@hamin Indeed, looks like there is no ready-made solution for this, so one would have to implement the Airplay v2 protocol for audio streaming in Ruby. :)

**Comment by Burgestrand** [comment]
Would be cool, but it’s probably a better idea to just write a CoreAudio audio driver for Hallon instead.
