### ISSUE TITLE
Track load timeout

### ISSUE THREAD

**Issue by chrblabla** [Burgestrand/Hallon#84]
@Burgestrand I hate to break the party, but now (running Hallon 0.14.0) I get timeout errors on loading tracks. Both with `track.load` and `session.wait_for {track.loaded?}`. Even extending the timeout period didn't help.
Here's some code I ran, including the exception:

```
>> starred = Hallon::User.new("andythawkins").starred
=> <Hallon::Playlist address=0x77841c0>
>> starred.loaded?
=> false
>> starred.load
=> <Hallon::Playlist address=0x77841c0>
>> starred.loaded?
=> true
>> starred.tracks.first
=> <Hallon::Playlist::Track address=0x7f10242a8af0>
>> t = starred.tracks.first
t.l=> <Hallon::Playlist::Track address=0x7f10242a8af0>
>> t.loaded?
=> false
>> t.load
Hallon::TimeoutError: execution expired
    /app/.bundle/gems/ruby/1.9.1/gems/hallon-0.14.0/lib/hallon/loadable.rb:17:in `sleep'
    /app/.bundle/gems/ruby/1.9.1/gems/hallon-0.14.0/lib/hallon/loadable.rb:17:in `block in load'
    /app/.bundle/gems/ruby/1.9.1/gems/hallon-0.14.0/lib/hallon/loadable.rb:9:in `load'
    /home/heroku_rack/lib/console.rb:158:in `block (2 levels) in <top (required)>'
```

**Comment by Burgestrand** [comment]
If this times out or not depends entirely on how long Hallon is allowed to try and load it. The default timeout is for _five_ seconds. If you do `track.load`, and the track does not load within five seconds, Hallon will raise a Hallon::TimeoutError.

Now, sometimes libspotify will take ages to load something. I’ve had times as long as a minute to load a playlist container. If you want to wait for something to load, and don’t care how long it will take, you can set the load timeout to 0 or nil.

```
Hallon.load_timeout = 0
```

This will cause _all_ loads to wait as long as necessary. If libspotify never manages to load an object, it will wait forever.

You can also set this property individually for each load.

```
track.load(0)
```

Keep in mind, some objects support an error status (like [AlbumBrowse#status](http://rubydoc.info/github/Burgestrand/Hallon/Hallon/AlbumBrowse#status-instance_method)). It allows Hallon to know if a permanent error is blocking the object from loading, and Hallon will raise an error if such an error occurs. Not all objects support this property however (Albums, Artists, and a few more), and Hallon will always wait the full timeout time if those objects cannot load.

So from what I can see, this is working as intended. I’ll let this issue stay open for some discussion if necessary, or if I misunderstood you :)

**Comment by chrblabla** [comment]
Thanks again for the quick reply. I already adjusted the timeout and used `session.wait_for {track.loaded?}`, which - as far as I understand - does not time out. But I haven't been able to see the track loading complete. This might be with specific tracks, but still.
Did you try to run 0.14.0 on Heroku as well? That's where my problems occur.

**Comment by Burgestrand** [comment]
Indeed, `session.wait_for { track.loaded? }` will not time out with an error. There may be multiple reasons to why a track might not load, however. I’ll give it a try on Heroku as well and see what I come up with. :)

**Comment by Burgestrand** [comment]
Aye, I tried running it on Heroku now (and updated [hallon-heroku](https://github.com/Burgestrand/hallon-heroku) as well). It’s up and running now on [http://hallon.herokuapp.com/](http://hallon.herokuapp.com/spotify:artist:2xerlUK5DItGhIhWOImdtS). It’s working awfully speedy.

Had a few tracks and artists in development that refused to load… like ever. Unfortunately, libspotify does not allow you to retrieve the status for these objects so there’s no way of knowing if it simply needs more time or if some kind of permanent error occurred.

**Comment by chrblabla** [comment]
Alright, I just let it timeout with a retry, this solves it for me now. Thank you very much for your support!

**Comment by Burgestrand** [comment]
@cptobvious And thank you, for reporting these bugs. Found a few others during tracking down your bugs as well! :)
