### ISSUE TITLE
Make a Hallon client for Play

### ISSUE THREAD

**Issue by Burgestrand** [Burgestrand/Hallon#94]
Examples of clients: https://github.com/play/play/tree/master/lib/play/clients

**Comment by jaime1988** [comment]
Hi! 
Would it be possible to play a song on client side? the link throws a 404

**Comment by Burgestrand** [comment]
It turns out Play has changed the way it plays audio completely. :(

Before it allowed you to write audio drivers yourself, but now it appears it’s using Airfoil (http://www.rogueamoeba.com/airfoil/) to route audio, and resorts to using AppleScript to control both Airfoil and iTunes, which is now the only source of audio possible. AppleScript is used quite extensively all over the models now, so I’m afraid a Hallon client for Play is no longer possible by just writing a client, one’d have to fork Play and rip out the parts specific to AppleScript/iTunes and replace them with more generalized versions that allow non-iTunes song libraries (mainly). Playing audio _might_ be supported if Airfoil works with OpenAL, but one’d want a CoreAudio driver for Hallon for maximum compatibility.

So, sorry, but this issue is no longer on the roadmap.

**Comment by jaime1988** [comment]
ok,

Thanks for your answer!
